name: Main
on: [push]
env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}
jobs:
  build:
    name: Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        # preflight is a tool that makes sure your CI processes run securely and are safe to use. 
        # To learn more and install preflight, see here: https://github.com/SpectralOps/preflight
        run: curl -L "https://get.spectralops.io/latest/x/sh?dsn=$SPECTRAL_DSN" | preflight run
      - name: Scan
        run: $HOME/.spectral/spectral scan --ok
